# Generated by Django 4.2.2 on 2023-08-31 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationformmodel',
            name='course_type',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
